#!/bin/bash

declare -x COUNT_DOWN=0
declare -x POST_LIFT_OFF_DELAY=0
declare -x STATUS_DELAY=0
declare -x SHOW_ANIMATION=false

ROCKET_TESTING_PATH=/tmp/test-rockets/

rm -rf "${ROCKET_TESTING_PATH}" 2> /dev/null
mkdir -p "${ROCKET_TESTING_PATH}"

PWDD="$(pwd)"
cd "${ROCKET_TESTING_PATH}" || exit

bash "${PWDD}/${1}" "${2}"
