#!/bin/bash

print_color()
{
	RED='\033[0;31m'
	GREEN='\033[0;32m'
	NC='\033[0m' # No Color

	case "${1}" in
	red)
		COLOR=$RED
		;;
	green)
		COLOR=$GREEN
		;;
	esac

	# shellcheck disable=SC2059
	printf "${COLOR}$2${NC}"
}

read -r -p "Are you sure you want to destroy the rocket? [y/n]: " confirm

if [[ ${confirm} == y ]]; then
	echo "Destroying rocket - ${1}..."
	rm -rf "${1}"
	sleep 1
	print_color green "Done!\n"
else
	echo "Exiting without destroying!"
fi
